# Generated by Django 5.2.6 on 2025-10-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Cursos',
        ),
    ]
